apiVersion: v1
kind: Secret
metadata:
  name: ha-todo-publisher-secrets
  namespace: ha-todo-publisher
type: Opaque
stringData:
  WRITE_TOKENS: "cars:replace-with-generated-write-secret"
  READ_TOKENS: "cars:replace-with-generated-read-secret"
